### ISSUE TITLE
Trigger DCA deployment when schematic releases or when `develop` branch gets updated

### ISSUE THREAD

**Issue by linglp** [Sage-Bionetworks/schematic#1026]
**Is your feature request related to a problem? Please describe.**
Currently, we have to manually update DCA testing instance when the `develop` branch in schematic gets updated. We could modify our current github workflow so that it could send a post request to DCA's repo and redeploy DCA. 

Changes that would need to happen: 

On DCA github workflow:
- Find the workflow that controls deployment of the testing instance
- make sure that part of the workflow runs on `repository_dispatch`. See an example below: 
```
on:
  repository_dispatch:
    types: trigger-frontend
jobs:
  build:
    name: Run stuff
    runs-on: ubuntu-latest
    steps:
      - name: deployment
        run: 'echo "Triggered event text: ${{ github.event.client_payload.text }}"'

```

On schematic github workflow: 
- triggers a post request like this: 
```
      - name: Test front-end deployment
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/Sage-Bionetworks/data_curator/dispatches \
          -d '{"event_type": "trigger-frontend", "client_payload": { "text": "develop branch has been updated"}}'

``` 
- the access_token here has to have scope `repo`

**Describe the solution you'd like**

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
