### ISSUE TITLE
Improve the key/field names in the config.yaml file

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/schematic#335]
Once PR #334 is merged, we can think of improving the key/field names in the config file so they're more intuitive. This could entail reorganizing the YAML structure. Here are a few suggestions:

- Reorganize the structure so that everything Synapse-related is under the `synapse` top-level key and everything Google-related is under a `google` top-level key. 
- Add the file types that are expected in the key names. For example, change `location` to `jsonld_location`. 
- Is `file_type` included because the location could be a URL? If so, couldn't that be inferred from the `location` (_i.e._ if prefixed with `http://` or `ftp://`)? I wouldn't be surprised if there was a library that can load files regardless of whether they are local or remote if given a string. 
- Could `synapse_config` be set to `~/.synapseConfig` instead by default? Admittedly, this is more of a usability improvement rather than a clarity improvement. 

**Excerpt from [`config.yaml`](https://github.com/Sage-Bionetworks/schematic/blob/ffab34d4af1af13cfc813359340d26375d5c1fee/config.yml)**
```
# Do not change the 'definitions' section unless you know what you're doing
definitions:
  synapse_config: ".synapseConfig"
  creds_path: "credentials.json"
  token_pickle: "token.pickle"
  service_acct_creds: "quickstart-1560359685924-198a7114b6b5.json"

synapse:
  master_fileview: 'syn20446927'
  manifest_folder: 'manifests'
  manifest_filename: 'data/manifests/synapse_storage_manifest.csv'
  api_creds: 'syn21088684'

model:
  input:
    location: 'data/schema_org_schemas/HTAN.jsonld'
    file_type: 'local'
    validation_schema: 'data/validation_schemas/HTAN_validation_schema_FamilyHistory.json'
    log_location: 'data/json_schema_logs/json_schema_log.json'
  biothings:
    location: 'data/schema_org_schemas/biothings.jsonld'
```
